# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mi007\Desktop\AutoPwC\ExcelTools\ui\ui_src\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 197)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/xlsx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.src_dir_label = QtWidgets.QLabel(self.centralwidget)
        self.src_dir_label.setObjectName("src_dir_label")
        self.gridLayout_4.addWidget(self.src_dir_label, 0, 0, 1, 1)
        self.src_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.src_dir.setObjectName("src_dir")
        self.gridLayout_4.addWidget(self.src_dir, 0, 1, 1, 1)
        self.open_src_dir = QtWidgets.QPushButton(self.centralwidget)
        self.open_src_dir.setObjectName("open_src_dir")
        self.gridLayout_4.addWidget(self.open_src_dir, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 1)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout_3.addWidget(self.start, 3, 2, 1, 1)
        self.open_output_dir = QtWidgets.QPushButton(self.centralwidget)
        self.open_output_dir.setObjectName("open_output_dir")
        self.gridLayout_3.addWidget(self.open_output_dir, 3, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 1, 0, 1, 3)
        self.logs_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.logs_text.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logs_text.sizePolicy().hasHeightForWidth())
        self.logs_text.setSizePolicy(sizePolicy)
        self.logs_text.setMinimumSize(QtCore.QSize(725, 48))
        self.logs_text.setMaximumSize(QtCore.QSize(725, 48))
        self.logs_text.setObjectName("logs_text")
        self.gridLayout_3.addWidget(self.logs_text, 2, 0, 1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel文件格式转换器"))
        self.src_dir_label.setText(_translate("MainWindow", "选择文件夹路径"))
        self.open_src_dir.setText(_translate("MainWindow", "打开文件夹"))
        self.start.setText(_translate("MainWindow", "开始转换"))
        self.open_output_dir.setText(_translate("MainWindow", "打开输出文件夹"))
        self.menu.setTitle(_translate("MainWindow", "开始"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
